.PHONY: default
default:
	make -C generations/ok
	make -C generations/no-database
	make -C generations/replica-name
	make -C generations/replica-url
	make -C restore/latest-replica
	make -C snapshots/ok
	make -C snapshots/replica-name
	make -C snapshots/replica-url
	make -C wal/ok
	make -C wal/replica-name
	make -C wal/replica-url
