name: GCP Integration Tests
on: pull_request

jobs:
  gcp-integration-test:
    name: Run GCP Integration Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ inputs.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ inputs.os }}-go-

      - name: Extract GCP credentials
        run: 'echo "$GOOGLE_APPLICATION_CREDENTIALS" > /opt/gcp.json'
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - run: go test -v -run=TestReplicaClient ./integration -replica-type gcs
        env:
          GOOGLE_APPLICATION_CREDENTIALS:  /opt/gcp.json
          LITESTREAM_GCS_BUCKET:           integration.litestream.io
