name: golangci-lint
on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=10m
