name: Manual Integration Tests

on:
  workflow_dispatch:
    inputs:
      run_s3:
        description: 'Run S3 Integration Tests'
        required: false
        default: true
        type: boolean
      run_gcp:
        description: 'Run GCP Integration Tests'
        required: false
        default: false
        type: boolean
      run_abs:
        description: 'Run Azure Blob Storage Integration Tests'
        required: false
        default: false
        type: boolean
      pr_number:
        description: 'Pull Request Number (optional)'
        required: false
        type: string

env:
  GO_VERSION: "1.24"

jobs:
  checkout-pr:
    name: Checkout PR or Branch
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get-ref.outputs.ref }}
    steps:
      - name: Get PR ref if provided
        id: get-ref
        run: |
          if [ -n "${{ github.event.inputs.pr_number }}" ]; then
            echo "ref=refs/pull/${{ github.event.inputs.pr_number }}/head" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ github.ref }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-ref.outputs.ref }}

  s3-integration-test:
    name: S3 Integration Tests
    runs-on: ubuntu-latest
    needs: checkout-pr
    if: github.event.inputs.run_s3 == 'true'
    environment: integration-tests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.checkout-pr.outputs.ref }}

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go install ./cmd/litestream

      - name: Run S3 Integration Tests
        run: go test -v ./replica_client_test.go -integration s3
        env:
          LITESTREAM_S3_ACCESS_KEY_ID: ${{ secrets.LITESTREAM_S3_ACCESS_KEY_ID }}
          LITESTREAM_S3_SECRET_ACCESS_KEY: ${{ secrets.LITESTREAM_S3_SECRET_ACCESS_KEY }}
          LITESTREAM_S3_REGION: us-east-1
          LITESTREAM_S3_BUCKET: integration.litestream.io

  gcp-integration-test:
    name: GCP Integration Tests
    runs-on: ubuntu-latest
    needs: checkout-pr
    if: github.event.inputs.run_gcp == 'true'
    environment: integration-tests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.checkout-pr.outputs.ref }}

      - name: Extract GCP credentials
        run: 'echo "$GOOGLE_APPLICATION_CREDENTIALS" > /opt/gcp.json'
        shell: bash
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go install ./cmd/litestream

      - name: Run GCP Integration Tests
        run: go test -v ./replica_client_test.go -integration gcs
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /opt/gcp.json
          LITESTREAM_GCS_BUCKET: integration.litestream.io

  abs-integration-test:
    name: Azure Blob Storage Integration Tests
    runs-on: ubuntu-latest
    needs: checkout-pr
    if: github.event.inputs.run_abs == 'true'
    environment: integration-tests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.checkout-pr.outputs.ref }}

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go install ./cmd/litestream

      - name: Run Azure Integration Tests
        run: go test -v ./replica_client_test.go -integration abs
        env:
          LITESTREAM_ABS_ACCOUNT_NAME: ${{ secrets.LITESTREAM_ABS_ACCOUNT_NAME }}
          LITESTREAM_ABS_ACCOUNT_KEY: ${{ secrets.LITESTREAM_ABS_ACCOUNT_KEY }}
          LITESTREAM_ABS_BUCKET: integration