name: S3 Integration Tests
on: pull_request

jobs:
  test:
    name: Run S3 Integration Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ inputs.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ inputs.os }}-go-

      - run: go install ./cmd/litestream

      - run: go test -v -run=TestReplicaClient ./integration -replica-type s3
        env:
          LITESTREAM_S3_ACCESS_KEY_ID: ${{ secrets.LITESTREAM_S3_ACCESS_KEY_ID }}
          LITESTREAM_S3_SECRET_ACCESS_KEY: ${{ secrets.LITESTREAM_S3_SECRET_ACCESS_KEY }}
          LITESTREAM_S3_REGION: us-east-1
          LITESTREAM_S3_BUCKET: integration.litestream.io
