.PHONY: default
default:
	make -C find-latest-generation/ok
	make -C generation-time-bounds/ok
	make -C generation-time-bounds/snapshots-only
	make -C replica-client-time-bounds/ok
	make -C snapshot-time-bounds/ok
	make -C wal-time-bounds/ok
